### PR TITLE
support JuMP update to v0.21.2

### PR DESCRIPTION
**Pull request by amgad-naiem**
Added support for latest JuMP version changes

### CODE REVIEW

**Comment by amgad-naiem** [comment]
Btw all checks passed, but I'm not sure why they don't show up here
https://travis-ci.org/github/anriseth/MultiJuMP.jl/builds/692167080

**Comment by matbesancon** [comment]
Thanks for the upgrade!

**Comment by ericphanson** [comment]
I think a release was never tagged after this PR; someone on Slack today was having trouble because release MultiJuMP doesn't precompile with JuMP v0.21 and there is no [compat] information in the Project.toml for the package resolver to find a compatible version of JuMP. Could you tag a release and add compat? (There's info about [compat] here in case you aren't familiar: https://github.com/JuliaRegistries/General#automatic-merging-of-pull-requests).

**Comment by mlubin** [comment]
Another confused user: https://discourse.julialang.org/t/multijump-failed/49265

**Pull request merged**
