### PR TITLE
varDict -> objDict

### PR DESCRIPTION
**Pull request by anriseth**
Fix changes made by https://github.com/JuliaOpt/JuMP.jl/pull/1028

### CODE REVIEW

**Comment by anriseth** [comment]
objDict contains constraints as well. Need to do something else to extract the values of each variable...

**Comment by mlubin** [comment]
This is not a correct way to loop through all variables in the model. Use
```julia
[Variable(m,i) for i in 1:MathProgBase.numvar(m)]
```
instead.

**Comment by anriseth** [comment]
Thank you @mlubin !

**Comment by anriseth** [comment]
@bablookumarroy this should fix your problem with `tanaka.jl`. Note that I removed Julia 0.5 support, so you may wish to upgrade to Julia 0.6.

**Comment by bablookumarroy** [comment]
@anriseth Now its working fine.

**Pull request merged**
